src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Repository\AnimalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\HttpFoundation\File\File;
use App\Entity\InfoAnimal;

use Symfony\Component\Validator\Constraints as Assert;


#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: AnimalRepository::class)]
class Animal
{   
    #[Groups("animal:read")]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Groups("animal:read")]
    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[Groups("animal:read")]
    #[ORM\Column]
    private ?string $race = null;

    #[ORM\ManyToOne(inversedBy: 'animals')]
    #[Groups("animal:read")]
    private ?Habitat $Habitat = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[Assert\File(maxSize: "10024k", mimeTypes: ["image/webp"], mimeTypesMessage: "Please upload a valid image file")]
    #[Vich\UploadableField(mapping: "animal", fileNameProperty: "imageName")]
    private $imageFile;

    #[ORM\Column(type: "string",length:255, nullable: true)]
    #[Groups("animal:read")]
    private ?string $imageName = null;

    

    #[ORM\OneToMany(mappedBy: 'animal', targetEntity: Repas::class, cascade: ["remove"])]
    private Collection $repas;

    #[ORM\OneToMany(mappedBy: 'animal', targetEntity: InfoAnimal::class, orphanRemoval: true, cascade: ["remove"])]
    private Collection $infoAnimals;

    #[ORM\OneToMany(mappedBy: 'animal', targetEntity: AdditionalImages::class)]
    private Collection $additionalImages;

    
    public function __construct()
    {
        $this->repas = new ArrayCollection();
        $this->infoAnimals = new ArrayCollection();
        $this->additionalImages = new ArrayCollection();
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getRace(): ?string
    {
        return $this->race;
    }

    public function setRace(string $race): static
    {
        $this->race = $race;

        return $this;
    }


    public function getHabitat(): ?Habitat
    {
        return $this->Habitat;
    }

    public function setHabitat(?Habitat $Habitat): static
    {
        $this->Habitat = $Habitat;

        return $this;
    }

    

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }


    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): static
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;
        if (null !== $imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }


    /**
     * @return Collection<int, repas>
     */
    public function getRepas(): Collection
    {
        return $this->repas;
    }

    public function addRepa(repas $repa): static
    {
        if (!$this->repas->contains($repa)) {
            $this->repas->add($repa);
            $repa->setAnimal($this);
        }

        return $this;
    }

    public function removeRepa(repas $repa): static
    {
        if ($this->repas->removeElement($repa)) {
            // set the owning side to null (unless already changed)
            if ($repa->getAnimal() === $this) {
                $repa->setAnimal(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, InfoAnimal>
     */
    public function getInfoAnimals(): Collection
    {
        return $this->infoAnimals;
    }

    public function addInfoAnimal(InfoAnimal $infoAnimal): static
    {
        if (!$this->infoAnimals->contains($infoAnimal)) {
            $this->infoAnimals->add($infoAnimal);
            $infoAnimal->setAnimal($this);
        }

        return $this;
    }

    public function removeInfoAnimal(InfoAnimal $infoAnimal): static
    {
        if ($this->infoAnimals->removeElement($infoAnimal)) {
            // set the owning side to null (unless already changed)
            if ($infoAnimal->getAnimal() === $this) {
                $infoAnimal->setAnimal(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, AdditionalImages>
     */
    public function getAdditionalImages(): Collection
    {
        return $this->additionalImages;
    }

    public function addAdditionalImage(AdditionalImages $additionalImage): static
    {
        if (!$this->additionalImages->contains($additionalImage)) {
            $this->additionalImages->add($additionalImage);
            $additionalImage->setAnimal($this);
        }

        return $this;
    }

    public function removeAdditionalImage(AdditionalImages $additionalImage): static
    {
        if ($this->additionalImages->removeElement($additionalImage)) {
            // set the owning side to null (unless already changed)
            if ($additionalImage->getAnimal() === $this) {
                $additionalImage->setAnimal(null);
            }
        }

        return $this;
    }




    

}

src/Controller/AnimalController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Doctrine\ODM\MongoDB\DocumentManager;

use App\Entity\Animal;
use App\Repository\AnimalRepository;
use App\Document\AnimalVisit;
use App\Entity\InfoAnimal;
use App\Exception\AnimalNotFoundException;
use App\Repository\InfoAnimalRepository;
use Doctrine\ORM\EntityManager;
use PHPUnit\Util\Json;
use App\Entity\AdditionalImages;
use App\Repository\AdditionalImagesRepository;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/animal', name: 'app_animal_')]
class AnimalController extends AbstractController
{

    public function __construct(
        private EntityManagerInterface $entityManager,
        private SerializerInterface $serializer,
        private DocumentManager $documentManager,
        )
    {
        $this->entityManager=$entityManager;
        $this->serializer=$serializer;
        $this->documentManager = $documentManager;
    }

    #[Route('/show/{id}', name: 'show', methods: ['GET'])]
    public function showAnimal(int $id, 
    AnimalRepository $animalRepo, 
    DocumentManager $documentManager, 
    InfoAnimalRepository $infoAnimalRepo, 
    ): Response
    {   
        $animal = $animalRepo->find($id);
        if(!$animal){
            throw new AnimalNotFoundException(); 
        }
        $infoAnimal = $infoAnimalRepo->findBy(
            ['animal' => $id],
            ['createdAt' => 'DESC'],
            1
        );

        $visit = $documentManager->getRepository(AnimalVisit::class)->findOneBy(['animalId' => $id]);
        if(!$visit){
            $visit = new AnimalVisit();
            $visit->setAnimalId($id);
            $visit->setAnimalName($animalRepo->find($id)->getPrenom());
        }
        $visit->incrementVisits();
        $documentManager->persist($visit);
        $documentManager->flush();
        return $this->render('animal/show.html.twig', [
            'animal' => $animal,
            'infoAnimal' => $infoAnimal,
        ]);
    }

    #[IsGranted('ROLE_USER',)]
    #[Route('/all', name: 'getAnimals', methods: ['GET'])]
    public function getAnimals(AnimalRepository $animalRepository): JsonResponse
    {
        try{
        $animals = $animalRepository->findAll();
        $context = ['groups' => 'animal:read'];
        return JsonResponse::fromJsonString($this->serializer->serialize(
            $animals, 'json', $context),
            Response::HTTP_OK);
        
        } catch (\Exception $e) {
            return new JsonResponse([
                'error' => 'An error occurred',
                'message' => $e->getMessage()
            ], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    #[Route('/getImages/{id}', name: 'getImages', methods: ['GET'])]
    public function getImages(int $id, AnimalRepository $animalRepo, AdditionalImagesRepository $imageRepo, SerializerInterface $serializer): JsonResponse
    {
    try{
        $images = $imageRepo->findBy(['animal' => $id], ['createdAt' => 'DESC']);
        if(!$images){
            $images = null;
        }
        return new JsonResponse($serializer->serialize($images, 'json', ['groups' => 'image:read']));
    }
    catch(\Exception $e){
        return new JsonResponse($e->getMessage(), 500);
    }
    }
    

    
}

templates/animal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AnimalController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/Seb/Desktop/arcadia git clone/Arcadia2/Arcadia/src/Controller/AnimalController.php'|file_link(0) }}">src/Controller/AnimalController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/Seb/Desktop/arcadia git clone/Arcadia2/Arcadia/templates/animal/index.html.twig'|file_link(0) }}">templates/animal/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/animal/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{animal.prenom}}{% endblock %}

{% block body %}
<link rel="stylesheet" href="{{ asset('css/showAnimal.css') }}">

<style>
    body{
        background-image: url( {{asset('images/parc/jungle_bg_.jpg')}} );
    }

</style>
<div class="page-container">
    {# navigation desktop #}
    <div class="navbar mt-5 animal-navbar d-none d-lg-block">
            <H2><a class="nav-item d-none d-lg-block ml-3" href="{{ path('app_habitat_index') }}">Voir les Habitats</a><H2>
            <H2 class="nav-item d-none d-lg-block infoBtn text-white" role="button" aria-label="Informations animal"> Information sur l'animal</H2>
            <H2 class="nav-item d-none d-lg-block imageBtn text-white" role="button" aria-label="Gallerie photos">Gallerie photo</H2>
    </div>
    {# navigation mobile #}
    <div class="navbar animal-navbar mt-5 mb-2 d-flex justify-content-around d-lg-none">
        <H2><a class="nav-item d-lg-none" href="{{ path('app_habitat_index') }}"><i class="fa-solid fa-arrow-left"></i></a></H2>
        <H2><a class="nav-item d-lg-none infoBtn" role="button" aria-label="Informations animal"><i class="fa-regular fa-clipboard"></i></a></H2>
        <H2><a class="nav-item d-lg-none imageBtn" role="button" aria-label="Gallerie photos"><i class="fa-regular fa-image"></i></a></H2>
    </div>


    <div class="animal-presentation container" id="infoContainer">
        <div class="row">            
            <div class="col-lg-6 col-md-12 col-sm-12 d-flex justify-content-center">
                <img src="{{asset('images/animal/'~ animal.imageName)}}" alt="animal" class="animal-image">
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 card card-animal mb-5">
                <div class="card-header text-center">
                    <h1 class="card-title">{{animal.prenom}}</h1>
                </div>
                <div class="card-body">
                <input type="hidden" id="animalId" value="{{animal.id}}">
                <p>Race : {{animal.race}}</p>
                <p>Date d'arrivée : {{animal.createdAt | date('d/m/Y')}}</p>
                {% if animal.habitat is not null %}
                <p>Habitat : {{animal.habitat.nom}}</p>
                {% endif %}
                </div>
                <div class="card-footer text-center">
                    <h2>Notes vétérinaires :</h2>
                    {% if infoAnimal == null %}
                    <p>Pas de note pour le moment</p>
                    {% else %}
                        {% for infoAnimal in infoAnimal %}
                                <h3>{{ infoAnimal.createdAt | date('d-m-Y') }}</h3>
                                <p class="card-text">Etat de l'animal : {{ infoAnimal.etat }}</p>
                                {% if infoAnimal.details != null %}
                                    <p class="card-text">Détails : {{ infoAnimal.details }}</p>
                                {% endif %}
                                <p class="card-text">Nourriture : {{ infoAnimal.nourriture.nom }}</p>
                                <p class="card-text">Quantité recommandé : {{ infoAnimal.grammage }}g</p>
                            
                        {% endfor %}
                    {% endif %}
                </div>         
            </div>
        </div>
    </div>

    <div  class="container" id="gallerie-container">
        <div class="row" id="gallerie">
            
        </div>
    </div>

</div>





<script src="{{ asset('js/publicShowAnimal.js') }}"></script>
{% endblock %}

{% block javascripts %}
{% endblock %}